### ISSUE TITLE
Unresponsive UI

### ISSUE THREAD

**Issue by siinch** [mmtrt/legendsofruneterra#3]
Hi.

The majority of the times when I launch the game, the UI remains unresponsive. By unresponsive I mean that I can not click the buttons in the game. It is unclear to me why it sometimes works and sometimes not.

I am using Lubuntu. Maybe that is a part of the reason.

Let me know if I can be helpful in any way

Kind regards
Simon

**Comment by mmtrt** [comment]
try using wine virtual desktop from `winecfg`

`legendsofruneterra.winecfg`

![winecfg](https://user-images.githubusercontent.com/2322598/79573924-cdaa4200-80d8-11ea-9f49-cca32c1ce277.png)

**Comment by pabloVoorvaart** [comment]
Hi,
i fixed this issue by running `legendsofruneterra.winecfg` as mmtrt said, and then ticking the "Automatically capture the mouse in full-screen windows".

I dont think there is a need to enable "Emulate a virtual desktop".

Please report back if this fixed the issue. Also if it did it would be nice to implement it in the snap config if possible. @mmtrt 

Cheers, Pablo.

**Comment by pabloVoorvaart** [comment]
Also, if the after switching between applications the UI is unresponsive, apply this fix:

https://www.reddit.com/r/wine_gaming/comments/e1jhoj/wine_fullscreen_issue/

**Comment by QuestionQuest117** [comment]
I would like to point out that while implementing this winecfg fix works for when the program starts up, should you tab out of the game and tab back in, the issue persists. Is there any way of fixing it permanently?

Also while you tab out with the game still running, an old display of open programs overlays what programs are running, requiring you to blindly select where on the taskbar the program is (on POPOS! KDE at least)
